DROP TABLE IF EXISTS DETALLE_PEDIDO;
DROP TABLE IF EXISTS PEDIDO_FARMACIA;
DROP TABLE IF EXISTS MEDICAMENTO;
DROP TABLE IF EXISTS MEDICO;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS PERSONA;
DROP TABLE IF EXISTS ESPECIALIDAD;
DROP PROCEDURE IF EXISTS REGISTRAR_MEDICAMENTO;
DROP PROCEDURE IF EXISTS REGISTRAR_PACIENTE;
DROP PROCEDURE IF EXISTS LISTAR_PACIENTES;
DROP PROCEDURE IF EXISTS REGISTRAR_PEDIDO;
DROP PROCEDURE IF EXISTS REGISTRAR_DETALLE_PEDIDO;
DROP PROCEDURE IF EXISTS LISTAR_MEDICAMENTOS;
DROP PROCEDURE IF EXISTS REGISTRAR_MEDICO;
DROP PROCEDURE IF EXISTS LISTAR_MEDICOS;
DROP PROCEDURE IF EXISTS REGISTRAR_ESPECIALIDAD;
DROP PROCEDURE IF EXISTS CANT_NOMBRE_MED_ESP;
CREATE TABLE PERSONA(
	ID_PERSONA INT PRIMARY KEY AUTO_INCREMENT,
    DNI VARCHAR(8) UNIQUE,
    NOMBRES VARCHAR(50),
    APELLIDO_PATERNO VARCHAR(35),
    SEXO CHAR,
    EDAD INT,
    ESTADO_CIVIL CHAR
);

CREATE TABLE PACIENTE(
	ID_PACIENTE INT PRIMARY KEY,
    APELLIDO_MATERNO VARCHAR(35),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PERSONA (ID_PERSONA)
);

CREATE TABLE MEDICAMENTO(
	ID_MEDICAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(25),
    PRESENTACION VARCHAR(15),
    COSTO_UNIDAD DECIMAL(6,2),
    FARMACEUTICA VARCHAR(25),
    GENERICO_SN BOOL
);
CREATE TABLE ESPECIALIDAD(
	ID_ESPECIALIDAD INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50),
	CLASIFICACION VARCHAR(50)
);

CREATE TABLE PEDIDO_FARMACIA(
	ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    FID_PACIENTE INT,
    FECHA_HORA DATETIME,
    TOTAL DECIMAL(6,2),
    FOREIGN KEY (FID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);

CREATE TABLE DETALLE_PEDIDO(
	ID_DETALLE_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    FID_PEDIDO INT,
    FID_MEDICAMENTO INT,
    CANTIDAD INT,
    SUBTOTAL DECIMAL(6,2),
    FOREIGN KEY (FID_PEDIDO) REFERENCES PEDIDO_FARMACIA(ID_PEDIDO),
    FOREIGN KEY (FID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);
CREATE TABLE EMPLEADO(
	FID_EMPLEADO INT PRIMARY KEY,
	SALARIO DECIMAL(10,2) NOT NULL,
	DEDICACION VARCHAR(2),
	FOREIGN KEY (FID_EMPLEADO) REFERENCES PERSONA(ID_PERSONA)
);
CREATE TABLE MEDICO(
	FID_MEDICO INT PRIMARY KEY,
	FID_ESPECIALIDAD INT,
	COLEGIATURA VARCHAR(7),
	FOREIGN KEY (FID_MEDICO) REFERENCES EMPLEADO(FID_EMPLEADO),
	FOREIGN KEY (FID_ESPECIALIDAD) REFERENCES ESPECIALIDAD(ID_ESPECIALIDAD)
);

DELIMITER //
CREATE PROCEDURE REGISTRAR_PACIENTE(
	_DNI VARCHAR(8),
    _NOMBRES VARCHAR(50),
    _APELLIDO_PATERNO VARCHAR(35),
    _APELLIDO_MATERNO VARCHAR(35),
    _SEXO CHAR,
    _EDAD INT,
    _ESTADO_CIVIL CHAR
)
BEGIN
	DECLARE _ID INT;
	INSERT INTO PERSONA (DNI,NOMBRES,APELLIDO_PATERNO,SEXO,EDAD,ESTADO_CIVIL)
    VALUES(_DNI,_NOMBRES,_APELLIDO_PATERNO,_SEXO,_EDAD,_ESTADO_CIVIL);
    SET _ID = last_insert_id();
    INSERT INTO PACIENTE (ID_PACIENTE,APELLIDO_MATERNO) VALUES (_ID,_APELLIDO_MATERNO);
END //
CREATE PROCEDURE REGISTRAR_MEDICAMENTO(
	_NOMBRE VARCHAR(25),
    _PRESENTACION VARCHAR(15),
    _COSTO_UNIDAD DECIMAL(6,2),
    _FARMACEUTICA VARCHAR(25),
    _GENERICO_SN BOOL
)
BEGIN
	INSERT INTO MEDICAMENTO (NOMBRE,PRESENTACION,COSTO_UNIDAD,FARMACEUTICA,GENERICO_SN)
    VALUES (_NOMBRE,_PRESENTACION,_COSTO_UNIDAD,_FARMACEUTICA,_GENERICO_SN);
END //

DELIMITER ;
CALL REGISTRAR_PACIENTE("18720019","JUAN","CHAVEZ","SOLAR",'M',32,'S');
CALL REGISTRAR_PACIENTE("10067291","PEDRO","PEREZ","MARTINEZ",'M',22,'C');
CALL REGISTRAR_PACIENTE("12988102","SOFIA","LEON","TORRES",'F',19,'S');
CALL REGISTRAR_PACIENTE("15321082","ROMINA","NARVAEZ","COSTA",'F',28,'D');
CALL REGISTRAR_PACIENTE("52208251","MAGALY","PAREDES","CASTILLO",'F',23,'S');

CALL REGISTRAR_MEDICAMENTO("PANADOL","500 MG",1.2,"GLAXOSMITHKLINE S.A.",0);
CALL REGISTRAR_MEDICAMENTO("PANADOL","1 G",2.4,"GLAXOSMITHKLINE S.A.",0);
CALL REGISTRAR_MEDICAMENTO("IBUPROFENO","200 MG",1.0,"FARMA PERU",1);
CALL REGISTRAR_MEDICAMENTO("IBUPROFENO","400 MG",1.8,"FARMA PERU",1);
CALL REGISTRAR_MEDICAMENTO("AMOXICILINA","250 MG",0.5,"FARMAINDUSTRIA",1);
CALL REGISTRAR_MEDICAMENTO("AMOXICILINA","500 MG",0.9,"FARMAINDUSTRIA",1);
CALL REGISTRAR_MEDICAMENTO("ALPRAZOLAN","0.5 MG",0.3,"QUALIX",1);
CALL REGISTRAR_MEDICAMENTO("ALPRAZOLAN","1 MG",0.5,"QUALIX",1);
CALL REGISTRAR_MEDICAMENTO("ALPRAZOLAN","2 MG",1.2,"QUALIX",1);
CALL REGISTRAR_MEDICAMENTO("SERTRALIN","20 MG",1.0,"PFIZER",1);
CALL REGISTRAR_MEDICAMENTO("SERTRALIN","50 MG",1.8,"PFIZER",1);
CALL REGISTRAR_MEDICAMENTO("SERTRALIN","100 MG",2.5,"PFIZER",1);
CALL REGISTRAR_MEDICAMENTO("CETIRIZINA","10 MG",1.6,"PHARMACHECK",0);
CALL REGISTRAR_MEDICAMENTO("DIGOXINA","0.25 MG",1.1,"P&SA",0);
CALL REGISTRAR_MEDICAMENTO("DIGOXINA","0.5 MG",2.0,"P&SA",0);
CALL REGISTRAR_MEDICAMENTO("NEUROBION","100 MG",1.4,"MERCK",1);
DELIMITER //
CREATE PROCEDURE LISTAR_PACIENTES()
BEGIN
	SELECT * FROM PERSONA INNER JOIN PACIENTE ON PERSONA.ID_PERSONA = PACIENTE.ID_PACIENTE;
END//
CREATE PROCEDURE LISTAR_MEDICAMENTOS()
BEGIN
	SELECT * FROM MEDICAMENTO;
END//
CREATE PROCEDURE REGISTRAR_PEDIDO(
	IN _FID_PACIENTE INT,
    IN _TOTAL DECIMAL(6,2)
)
BEGIN
	INSERT INTO PEDIDO_FARMACIA(FID_PACIENTE,TOTAL,FECHA_HORA) VALUES(_FID_PACIENTE,_TOTAL,NOW());
END//
CREATE PROCEDURE REGISTRAR_DETALLE_PEDIDO(
	IN _FID_PEDIDO INT,
    IN _FID_MEDICAMENTO INT,
    IN _CANTIDAD INT,
    IN _SUBTOTAL DECIMAL(6,2)
)
BEGIN
	INSERT INTO DETALLE_PEDIDO(FID_PEDIDO,FID_MEDICAMENTO,CANTIDAD,SUBTOTAL)
    VALUES (_FID_PEDIDO,_FID_MEDICAMENTO,_CANTIDAD,_SUBTOTAL);
END//
CREATE PROCEDURE LISTAR_MEDICOS()
BEGIN
	SELECT * FROM MEDICO INNER JOIN EMPLEADO ON MEDICO.FID_MEDICO = EMPLEADO.FID_EMPLEADO INNER JOIN PERSONA ON PERSONA.ID_PERSONA = EMPLEADO.FID_EMPLEADO INNER JOIN ESPECIALIDAD ON ESPECIALIDAD.ID_ESPECIALIDAD = MEDICO.FID_ESPECIALIDAD;
END//
CREATE PROCEDURE REGISTRAR_MEDICO(
	OUT _ID_PERSONA INT,
	IN _DNI VARCHAR(8),
    IN _NOMBRES VARCHAR(50),
    IN _APELLIDO_PATERNO VARCHAR(35),
    IN _SEXO CHAR,
    IN _EDAD INT,
    IN _ESTADO_CIVIL CHAR,
	IN _SALARIO DECIMAL(10,2),
	IN _DEDICACION VARCHAR(2),
	IN _COLEGIATURA VARCHAR(7),
	IN _ID_ESPECIALIDAD INT
)
BEGIN
	INSERT INTO PERSONA(DNI,NOMBRES,APELLIDO_PATERNO,SEXO,EDAD,ESTADO_CIVIL)
	VALUES (_DNI,_NOMBRES,_APELLIDO_PATERNO,_SEXO,_EDAD,_ESTADO_CIVIL);
	SET _ID_PERSONA = @@last_insert_id;
	INSERT INTO EMPLEADO(FID_EMPLEADO,SALARIO,DEDICACION) VALUES (_ID_PERSONA, _SALARIO, _DEDICACION);
	INSERT INTO MEDICO(FID_MEDICO,COLEGIATURA,FID_ESPECIALIDAD) VALUES(_ID_PERSONA,_COLEGIATURA,_ID_ESPECIALIDAD);
END//
CREATE PROCEDURE REGISTRAR_ESPECIALIDAD(
	IN _NOMBRE VARCHAR (50),
	IN _CLASIFICACION VARCHAR (50)
)
BEGIN
	INSERT INTO ESPECIALIDAD(NOMBRE, CLASIFICACION) VALUES (_NOMBRE, _CLASIFICACION);
END//
CREATE PROCEDURE CANT_NOMBRE_MED_ESP(
	OUT _CANTIDAD_ESP1 INT,
	OUT _NOMBRE_ESP1 VARCHAR(50),
	OUT _CANTIDAD_ESP2 INT,
	OUT _NOMBRE_ESP2 VARCHAR(50),
	IN _ID_ESPECIALIDAD1 INT,
	IN _ID_ESPECIALIDAD2 INT
)
BEGIN
	SET _CANTIDAD_ESP1 = (SELECT COUNT(*) AS CANTIDAD FROM MEDICO WHERE FID_ESPECIALIDAD = _ID_ESPECIALIDAD1);
	SET _NOMBRE_ESP1 = (SELECT NOMBRE FROM ESPECIALIDAD WHERE ID_ESPECIALIDAD = _ID_ESPECIALIDAD1);
	SET _CANTIDAD_ESP2 = (SELECT COUNT(*) AS CANTIDAD FROM MEDICO WHERE FID_ESPECIALIDAD = _ID_ESPECIALIDAD2);
	SET _NOMBRE_ESP2 = (SELECT NOMBRE FROM ESPECIALIDAD WHERE ID_ESPECIALIDAD = _ID_ESPECIALIDAD2);
END//
DELIMITER ;
CALL REGISTRAR_ESPECIALIDAD("DERMATOLOGIA","QUIRURGICA");
CALL REGISTRAR_ESPECIALIDAD("PSIQUIATRIA","CLINICA");
CALL REGISTRAR_MEDICO(@ID,"10982771","VANESSA","ALVAREZ",'F',28,'S',2500.00,"TC","1809853",1);
CALL REGISTRAR_MEDICO(@ID,"10265111","JORGE","SANCHEZ",'M',37,'C',3210.00,"TC","1298233",2);