//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNegocios.PartidosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicio/", ConfigurationName="PartidosWS.PartidosWS")]
    public interface PartidosWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/PartidosWS/listarPaisesRequest", ReplyAction="http://Servicio/PartidosWS/listarPaisesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LogicaNegocios.PartidosWS.listarPaisesResponse listarPaises(LogicaNegocios.PartidosWS.listarPaisesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/PartidosWS/listarPaisesRequest", ReplyAction="http://Servicio/PartidosWS/listarPaisesResponse")]
        System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.listarPaisesResponse> listarPaisesAsync(LogicaNegocios.PartidosWS.listarPaisesRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/PartidosWS/eliminarPartidoRequest", ReplyAction="http://Servicio/PartidosWS/eliminarPartidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LogicaNegocios.PartidosWS.eliminarPartidoResponse eliminarPartido(LogicaNegocios.PartidosWS.eliminarPartidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/PartidosWS/eliminarPartidoRequest", ReplyAction="http://Servicio/PartidosWS/eliminarPartidoResponse")]
        System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.eliminarPartidoResponse> eliminarPartidoAsync(LogicaNegocios.PartidosWS.eliminarPartidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/PartidosWS/listarPartidosRequest", ReplyAction="http://Servicio/PartidosWS/listarPartidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LogicaNegocios.PartidosWS.listarPartidosResponse listarPartidos(LogicaNegocios.PartidosWS.listarPartidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/PartidosWS/listarPartidosRequest", ReplyAction="http://Servicio/PartidosWS/listarPartidosResponse")]
        System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.listarPartidosResponse> listarPartidosAsync(LogicaNegocios.PartidosWS.listarPartidosRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/PartidosWS/registrarPartidoRequest", ReplyAction="http://Servicio/PartidosWS/registrarPartidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LogicaNegocios.PartidosWS.registrarPartidoResponse registrarPartido(LogicaNegocios.PartidosWS.registrarPartidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/PartidosWS/registrarPartidoRequest", ReplyAction="http://Servicio/PartidosWS/registrarPartidoResponse")]
        System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.registrarPartidoResponse> registrarPartidoAsync(LogicaNegocios.PartidosWS.registrarPartidoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class pais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cATEGORIA_SORTEOField;
        
        private string gRUPOField;
        
        private int iD_PAIS_CLASIFICADOField;
        
        private string nOMBREField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int CATEGORIA_SORTEO {
            get {
                return this.cATEGORIA_SORTEOField;
            }
            set {
                this.cATEGORIA_SORTEOField = value;
                this.RaisePropertyChanged("CATEGORIA_SORTEO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string GRUPO {
            get {
                return this.gRUPOField;
            }
            set {
                this.gRUPOField = value;
                this.RaisePropertyChanged("GRUPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int ID_PAIS_CLASIFICADO {
            get {
                return this.iD_PAIS_CLASIFICADOField;
            }
            set {
                this.iD_PAIS_CLASIFICADOField = value;
                this.RaisePropertyChanged("ID_PAIS_CLASIFICADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class partido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eQUIPO_AField;
        
        private int eQUIPO_BField;
        
        private int gOLES_EQUIPO_AField;
        
        private int gOLES_EQUIPO_BField;
        
        private bool jUGADOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int EQUIPO_A {
            get {
                return this.eQUIPO_AField;
            }
            set {
                this.eQUIPO_AField = value;
                this.RaisePropertyChanged("EQUIPO_A");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int EQUIPO_B {
            get {
                return this.eQUIPO_BField;
            }
            set {
                this.eQUIPO_BField = value;
                this.RaisePropertyChanged("EQUIPO_B");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int GOLES_EQUIPO_A {
            get {
                return this.gOLES_EQUIPO_AField;
            }
            set {
                this.gOLES_EQUIPO_AField = value;
                this.RaisePropertyChanged("GOLES_EQUIPO_A");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int GOLES_EQUIPO_B {
            get {
                return this.gOLES_EQUIPO_BField;
            }
            set {
                this.gOLES_EQUIPO_BField = value;
                this.RaisePropertyChanged("GOLES_EQUIPO_B");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool JUGADO {
            get {
                return this.jUGADOField;
            }
            set {
                this.jUGADOField = value;
                this.RaisePropertyChanged("JUGADO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPaises", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class listarPaisesRequest {
        
        public listarPaisesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPaisesResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class listarPaisesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LogicaNegocios.PartidosWS.pais[] @return;
        
        public listarPaisesResponse() {
        }
        
        public listarPaisesResponse(LogicaNegocios.PartidosWS.pais[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPartido", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class eliminarPartidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LogicaNegocios.PartidosWS.partido arg0;
        
        public eliminarPartidoRequest() {
        }
        
        public eliminarPartidoRequest(LogicaNegocios.PartidosWS.partido arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPartidoResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class eliminarPartidoResponse {
        
        public eliminarPartidoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPartidos", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class listarPartidosRequest {
        
        public listarPartidosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPartidosResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class listarPartidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LogicaNegocios.PartidosWS.partido[] @return;
        
        public listarPartidosResponse() {
        }
        
        public listarPartidosResponse(LogicaNegocios.PartidosWS.partido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarPartido", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class registrarPartidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LogicaNegocios.PartidosWS.partido arg0;
        
        public registrarPartidoRequest() {
        }
        
        public registrarPartidoRequest(LogicaNegocios.PartidosWS.partido arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarPartidoResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class registrarPartidoResponse {
        
        public registrarPartidoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PartidosWSChannel : LogicaNegocios.PartidosWS.PartidosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartidosWSClient : System.ServiceModel.ClientBase<LogicaNegocios.PartidosWS.PartidosWS>, LogicaNegocios.PartidosWS.PartidosWS {
        
        public PartidosWSClient() {
        }
        
        public PartidosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartidosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartidosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartidosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicaNegocios.PartidosWS.listarPaisesResponse LogicaNegocios.PartidosWS.PartidosWS.listarPaises(LogicaNegocios.PartidosWS.listarPaisesRequest request) {
            return base.Channel.listarPaises(request);
        }
        
        public LogicaNegocios.PartidosWS.pais[] listarPaises() {
            LogicaNegocios.PartidosWS.listarPaisesRequest inValue = new LogicaNegocios.PartidosWS.listarPaisesRequest();
            LogicaNegocios.PartidosWS.listarPaisesResponse retVal = ((LogicaNegocios.PartidosWS.PartidosWS)(this)).listarPaises(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.listarPaisesResponse> LogicaNegocios.PartidosWS.PartidosWS.listarPaisesAsync(LogicaNegocios.PartidosWS.listarPaisesRequest request) {
            return base.Channel.listarPaisesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.listarPaisesResponse> listarPaisesAsync() {
            LogicaNegocios.PartidosWS.listarPaisesRequest inValue = new LogicaNegocios.PartidosWS.listarPaisesRequest();
            return ((LogicaNegocios.PartidosWS.PartidosWS)(this)).listarPaisesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicaNegocios.PartidosWS.eliminarPartidoResponse LogicaNegocios.PartidosWS.PartidosWS.eliminarPartido(LogicaNegocios.PartidosWS.eliminarPartidoRequest request) {
            return base.Channel.eliminarPartido(request);
        }
        
        public void eliminarPartido(LogicaNegocios.PartidosWS.partido arg0) {
            LogicaNegocios.PartidosWS.eliminarPartidoRequest inValue = new LogicaNegocios.PartidosWS.eliminarPartidoRequest();
            inValue.arg0 = arg0;
            LogicaNegocios.PartidosWS.eliminarPartidoResponse retVal = ((LogicaNegocios.PartidosWS.PartidosWS)(this)).eliminarPartido(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.eliminarPartidoResponse> LogicaNegocios.PartidosWS.PartidosWS.eliminarPartidoAsync(LogicaNegocios.PartidosWS.eliminarPartidoRequest request) {
            return base.Channel.eliminarPartidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.eliminarPartidoResponse> eliminarPartidoAsync(LogicaNegocios.PartidosWS.partido arg0) {
            LogicaNegocios.PartidosWS.eliminarPartidoRequest inValue = new LogicaNegocios.PartidosWS.eliminarPartidoRequest();
            inValue.arg0 = arg0;
            return ((LogicaNegocios.PartidosWS.PartidosWS)(this)).eliminarPartidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicaNegocios.PartidosWS.listarPartidosResponse LogicaNegocios.PartidosWS.PartidosWS.listarPartidos(LogicaNegocios.PartidosWS.listarPartidosRequest request) {
            return base.Channel.listarPartidos(request);
        }
        
        public LogicaNegocios.PartidosWS.partido[] listarPartidos() {
            LogicaNegocios.PartidosWS.listarPartidosRequest inValue = new LogicaNegocios.PartidosWS.listarPartidosRequest();
            LogicaNegocios.PartidosWS.listarPartidosResponse retVal = ((LogicaNegocios.PartidosWS.PartidosWS)(this)).listarPartidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.listarPartidosResponse> LogicaNegocios.PartidosWS.PartidosWS.listarPartidosAsync(LogicaNegocios.PartidosWS.listarPartidosRequest request) {
            return base.Channel.listarPartidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.listarPartidosResponse> listarPartidosAsync() {
            LogicaNegocios.PartidosWS.listarPartidosRequest inValue = new LogicaNegocios.PartidosWS.listarPartidosRequest();
            return ((LogicaNegocios.PartidosWS.PartidosWS)(this)).listarPartidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicaNegocios.PartidosWS.registrarPartidoResponse LogicaNegocios.PartidosWS.PartidosWS.registrarPartido(LogicaNegocios.PartidosWS.registrarPartidoRequest request) {
            return base.Channel.registrarPartido(request);
        }
        
        public void registrarPartido(LogicaNegocios.PartidosWS.partido arg0) {
            LogicaNegocios.PartidosWS.registrarPartidoRequest inValue = new LogicaNegocios.PartidosWS.registrarPartidoRequest();
            inValue.arg0 = arg0;
            LogicaNegocios.PartidosWS.registrarPartidoResponse retVal = ((LogicaNegocios.PartidosWS.PartidosWS)(this)).registrarPartido(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.registrarPartidoResponse> LogicaNegocios.PartidosWS.PartidosWS.registrarPartidoAsync(LogicaNegocios.PartidosWS.registrarPartidoRequest request) {
            return base.Channel.registrarPartidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogicaNegocios.PartidosWS.registrarPartidoResponse> registrarPartidoAsync(LogicaNegocios.PartidosWS.partido arg0) {
            LogicaNegocios.PartidosWS.registrarPartidoRequest inValue = new LogicaNegocios.PartidosWS.registrarPartidoRequest();
            inValue.arg0 = arg0;
            return ((LogicaNegocios.PartidosWS.PartidosWS)(this)).registrarPartidoAsync(inValue);
        }
    }
}
