/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package histograma;

import com.sun.glass.events.KeyEvent;
import java.awt.Graphics;
import java.awt.Rectangle;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class PanelHistograma extends javax.swing.JPanel {
    
    private int x = 50;
    private int y=200;
    private int xS =0;
    private int xM =0;
    private int xL =0;
    /**
     * Creates new form PanelHistograma
     */
    public PanelHistograma() {
        initComponents();        
    }
    
    public void paint(Graphics g){
        super.paint(g);
        g.fillRect(x, y-xS, 20, xS);
        g.fillRect(x+50, y-xM, 20, xM);
        g.fillRect(x+100, y-xL, 20, xL);
    }
    
    public void subirValor(int valor){
        if (valor <30){
            xS++;
            xS++;
            xS++;
        }
        else if(valor <70){
            xM++;
            xM++;
            xM++;
        }
        else {
            xL++;
            xL++;
            xL++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Número a añadir:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(446, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (jTextField1.getText().length() >3) jTextField1.setText(jTextField1.getText().substring(0, 2));
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                int numero = Integer.parseInt(jTextField1.getText());
                if(numero!=0){
                    subirValor(numero);
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "No es número");
            }
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    public static void main(String [] args) throws Exception{
        JFrame form = new JFrame();
        
        PanelHistograma panel = new PanelHistograma();
        form.add(panel);
        form.setVisible(true);
        form.setSize(700,700);
        
        panel.setVisible(true);
        panel.setSize(700,700);
        
        while(true){
            panel.repaint();
            Thread.sleep(10);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
