//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteC3_Serv_Java.AddWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddWS.SumarWSSoap")]
    public interface SumarWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumar", ReplyAction="*")]
        double sumar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> sumarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restar", ReplyAction="*")]
        double restar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> restarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplicar", ReplyAction="*")]
        double multiplicar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplicar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> multiplicarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dividir", ReplyAction="*")]
        double dividir(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dividir", ReplyAction="*")]
        System.Threading.Tasks.Task<double> dividirAsync(double a, double b);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludar", ReplyAction="*")]
        ClienteC3_Serv_Java.AddWS.saludarResponse saludar(ClienteC3_Serv_Java.AddWS.saludarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteC3_Serv_Java.AddWS.saludarResponse> saludarAsync(ClienteC3_Serv_Java.AddWS.saludarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saludarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saludar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteC3_Serv_Java.AddWS.saludarRequestBody Body;
        
        public saludarRequest() {
        }
        
        public saludarRequest(ClienteC3_Serv_Java.AddWS.saludarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class saludarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public saludarRequestBody() {
        }
        
        public saludarRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saludarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saludarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteC3_Serv_Java.AddWS.saludarResponseBody Body;
        
        public saludarResponse() {
        }
        
        public saludarResponse(ClienteC3_Serv_Java.AddWS.saludarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class saludarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string saludarResult;
        
        public saludarResponseBody() {
        }
        
        public saludarResponseBody(string saludarResult) {
            this.saludarResult = saludarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SumarWSSoapChannel : ClienteC3_Serv_Java.AddWS.SumarWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SumarWSSoapClient : System.ServiceModel.ClientBase<ClienteC3_Serv_Java.AddWS.SumarWSSoap>, ClienteC3_Serv_Java.AddWS.SumarWSSoap {
        
        public SumarWSSoapClient() {
        }
        
        public SumarWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SumarWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SumarWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SumarWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double sumar(double a, double b) {
            return base.Channel.sumar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> sumarAsync(double a, double b) {
            return base.Channel.sumarAsync(a, b);
        }
        
        public double restar(double a, double b) {
            return base.Channel.restar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> restarAsync(double a, double b) {
            return base.Channel.restarAsync(a, b);
        }
        
        public double multiplicar(double a, double b) {
            return base.Channel.multiplicar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> multiplicarAsync(double a, double b) {
            return base.Channel.multiplicarAsync(a, b);
        }
        
        public double dividir(double a, double b) {
            return base.Channel.dividir(a, b);
        }
        
        public System.Threading.Tasks.Task<double> dividirAsync(double a, double b) {
            return base.Channel.dividirAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteC3_Serv_Java.AddWS.saludarResponse ClienteC3_Serv_Java.AddWS.SumarWSSoap.saludar(ClienteC3_Serv_Java.AddWS.saludarRequest request) {
            return base.Channel.saludar(request);
        }
        
        public string saludar(string nombre) {
            ClienteC3_Serv_Java.AddWS.saludarRequest inValue = new ClienteC3_Serv_Java.AddWS.saludarRequest();
            inValue.Body = new ClienteC3_Serv_Java.AddWS.saludarRequestBody();
            inValue.Body.nombre = nombre;
            ClienteC3_Serv_Java.AddWS.saludarResponse retVal = ((ClienteC3_Serv_Java.AddWS.SumarWSSoap)(this)).saludar(inValue);
            return retVal.Body.saludarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteC3_Serv_Java.AddWS.saludarResponse> ClienteC3_Serv_Java.AddWS.SumarWSSoap.saludarAsync(ClienteC3_Serv_Java.AddWS.saludarRequest request) {
            return base.Channel.saludarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteC3_Serv_Java.AddWS.saludarResponse> saludarAsync(string nombre) {
            ClienteC3_Serv_Java.AddWS.saludarRequest inValue = new ClienteC3_Serv_Java.AddWS.saludarRequest();
            inValue.Body = new ClienteC3_Serv_Java.AddWS.saludarRequestBody();
            inValue.Body.nombre = nombre;
            return ((ClienteC3_Serv_Java.AddWS.SumarWSSoap)(this)).saludarAsync(inValue);
        }
    }
}
